name: Build blog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Build website
        run: make publish
      # - name: Deploy to GitHub Pages 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.1
      #   with:
      #     branch: gh-pages
      #     folder: output
      - name: Deploy to netlify
        run: netlify deploy --dir=output --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
